application: liveview
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /static/favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: liveview.app

libraries:
- name: jinja2
  version: latest
