CREATE TABLE UserAgent(
    id SERIAL UNIQUE,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
	device TEXT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT now()::TIMESTAMP,
    last_login TIMESTAMP WITHOUT TIME ZONE DEFAULT now()::TIMESTAMP);

CREATE TABLE Marker(
    id SERIAL UNIQUE,
    name TEXT UNIQUE NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    link TEXT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT now()::TIMESTAMP,
    updated TIMESTAMP WITHOUT TIME ZONE DEFAULT now()::TIMESTAMP);
